### ISSUE TITLE
Direct video data upload to Replicate API, bypassing S3 storage

### ISSUE THREAD

**Issue by sidedwards** [sidedwards/ai-meeting-transcriber#4]
## Description:
We should investigate the feasibility of skipping the S3 step and sending the video data directly to the Replicate API. This could potentially simplify the architecture and improve the performance of the application.

## Tasks:
- [x] Review the Replicate API documentation to check if it supports direct video data upload
- [ ] If feasible, modify scripts to send video data directly to the Replicate API
- [ ] Update the relevant functions and endpoints to handle direct video data transfer
- [ ] Update the documentation and architecture diagrams to reflect the changes, if implemented

**Comment by sidedwards** [comment]
According to the [docs](https://replicate.com/docs/topics/predictions/input-files), it seems our best option is using Local FIles.

> You can provide Replicate with a Blob, File, or Buffer object, and the library will handle the upload for you:

```
file_input="./path/to/your/file"
file=$(curl -s -X POST "https://api.replicate.com/v1/files" \
  -H "Authorization: Bearer $REPLICATE_API_TOKEN" \
  -H "Content-Type: multipart/form-data" \
  -F "content=@$file_input;type=application/octet-stream;title=$(basename $file_input)")
file_input_url=$(echo "$file" | jq -r '.urls.get')
```

While Data URI are supported, it's only recommended for files <1MB.

## Resources

- https://replicate.com/docs/topics/predictions/input-files

**Comment by sidedwards** [comment]
According to Replicate support, the max file size for their API is 100MiB, so s3 is still the best option.

Closing for now; will investigate other options down the road.
